[package]
name = "xenotech"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["vk"]
vk = ["ash"]

[target.'cfg(target_os = "windows")'.dependencies]
windows = { version = "0.51.0", features = ["Win32_UI_WindowsAndMessaging", "Win32_Foundation", "Win32_Graphics_Gdi"] }

[dependencies]
ash = { version = "0.37.3", features = ["linked"], optional = true }
